### ISSUE TITLE
Consider having "Kitchen sink"

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/orbit#1007]
Hi 👋 

I would like to propose an idea to have a kitchen sink -> simple React App with example usages of orbit components, one example here: https://foundation.zurb.com/sites/docs/v/5.5.3/components/kitchen_sink.html  + have a small set of cypress tests to verify such Kitchen sink app runs correctly -> to verify it all renders correctly - components can be bundled correctly, RTL works etc. -> to lower the risk of things like this: https://github.com/kiwicom/orbit-components/pull/985

**Comment by honzatmn** [comment]
Hi Jaroslav, we plan to add something like this to each component page on Orbit.Kiwi, in all variations it can possibly have.

Plus we'll update Themer to have more component there soon.

**Comment by jaroslav-kubicek** [comment]
cool! would be nice to have those tests included as well, so possible problems are discovered soon.
