### ISSUE TITLE
<InputField /> - too long error message

### ISSUE THREAD

**Issue by petrbr** [kiwicom/orbit#1153]
You can't read the whole error message if it overflows its container.

## Possible Solution
There should be a tooltip or at least classic html title.

## Context (Environment)
![image](https://user-images.githubusercontent.com/33488156/62126427-ef0b9980-b2cf-11e9-8a33-0b4ba6e5be1d.png)

**Comment by vepor** [comment]
This is going to be fixed and overall UX of error and help messages inside form components should improve. It's also actually an item of [Road to 1.0.0](https://orbit.kiwi/roadmap/road-to-1-0-0/).

Also, duplicate of #485

**Comment by mainframev** [comment]
Solved already in #2956
