### ISSUE TITLE
ChoiceGroup: allow radio buttons to be displayed in a row

### ISSUE THREAD

**Issue by jamessspanggg** [kiwicom/orbit#1879]
**Is your feature request related to a problem? Please describe.**
Currently choice group only allows `flex-direction: column`, which displays the radio buttons row by row. Would appreciate it if we can customise it such that it displays in a single row.

**Describe the solution you'd like**
Allow customisation of `flex-direction` to be row or col.

**Describe alternatives you've considered**
N.A

**Additional context**
N.A.

**Comment by vepor** [comment]
Sadly, we didn't have time to fully focus on this issue.
Moreover, after discussion with our designers we don't believe that there's proper use case for ChoiceGroup with row layout and therefore I'm closing it.
