### ISSUE TITLE
Sticky Component missing zIndex

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit#1906]
Hello , thank you again for the great work you are doing,
i was trying to use Sticky component and found that it doens't have higher zIndex value other elemnts are hidding it ,
is the a way to fix that ?
can we add some styling to the components?
thank you

**Comment by vepor** [comment]
Hello @kouloughli-hemza 👋 

Sorry for delay with the answer. Currently, `Sticky` is not that much handy for wider use cases. We have plan to refactor it and introduce additional API for it.

Expect PR in a few days. You can provide us more info regarding the z-index or your particular use case in the meantime 🙂

**Comment by kouloughli-hemza** [comment]
Thank you for the reply,
we want to add flight search bar and make it sticky when scrolling , same as in kiwi , but the cards holding search result are over sticky component , so we needed an api for z-index

**Comment by vepor** [comment]
I'm postponing this issue – we will focus on this in the future when we would like to implement a new framework how to works with z-indexes inside Orbit.

**Comment by mainframev** [comment]
Sticky component is deprecated and will be removed in the next release.
