### ISSUE TITLE
Update icons-svg-zip automatically

### ISSUE THREAD

**Issue by hrach** [kiwicom/orbit#2244]
**Is your feature request related to a problem? Please describe.**

Hi, I download https://images.kiwi.com/orbit-icons/orbit-svgs.zip to get all icons and it seems that this file is updated somehow manually since it is missing https://github.com/kiwicom/orbit/pull/2190.

**Describe the solution you'd like**

Update the file automatically.

**Comment by vepor** [comment]
@silvenon The best would be to setup automatic deployment for it with GitHub action.

I will mirror this issue to our to-do backlog and let you know once we will have any update about it @hrach.

**Comment by hrach** [comment]
I've just realized that the auto-updated zip can be found here: https://unpkg.com/@kiwicom/orbit-components%40latest/orbit-svgs.zip That's good enough for me :)
