### ISSUE TITLE
InputField placeholder not rendering Translation

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit#2300]
Hello,
i was working on InputField component and found that the placeholder is not working with <Translate /> , it prints [object object] as placeholder , is this an expected behavior ? in docs it said placeholder type is TranslationString . 
can you please explain the issue ?

```
 <InputField
          label={<Translate tKey="agency_name" />}
          placeholder={<Translate tKey="agency_name_placeholder" />}
          type="text"
 />
```

Thank You

**Comment by vepor** [comment]
Hello @kouloughli-hemza 👋 

By `TranslationString` we mean a function that returns `string`. Property `placeholder` is passed to the DOM element `input`, in the `placeholder` attribute that is attached to it, so therefore we don't offer a possibility.

The best would be to use `useTranslate` hook.

```jsx
const Example = () => {
  const translate = useTranslate()
  return <InputField placeholder={translate("agency_name_placeholder")} /> 
}
```

**Comment by kouloughli-hemza** [comment]
> Hello @kouloughli-hemza 
> 
> By `TranslationString` we mean a function that returns `string`. Property `placeholder` is passed to the DOM element `input`, in the `placeholder` attribute that is attached to it, so therefore we don't offer a possibility.
> 
> The best would be to use `useTranslate` hook.
> 
> ```js-jsx
> const Example = () => {
>   const translate = useTranslate()
>   return <InputField placeholder={translate("agency_name_placeholder")} /> 
> }
> ```

Thank you for the fast reply,
i understand now the idea , 
again i had to import the hook like this : 
import useTranslate from "@kiwicom/orbit-components/es/hooks/useTranslate";
importing it from lib wont work for me as we discused in previous translations issue ,

Thank you

**Comment by vepor** [comment]
I can't help you without full context of it @kouloughli-hemza 😞  There can be several reasons why you're encountering this kind of issue. Closing this one for now. If there will be any more issues feel free to open a new one 🙂
