### ISSUE TITLE
Expose enum/union types from TS and Flow definitions of components 

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit#2304]
We would like to export many possible enums/unions from TS/Flow definition, so our consumer can easily use them in the code bases if they utilize our components in their own way.

When they have the use case for it, the type checker can complain that the `type` can't be a `string`, e.g.:
```js
import Text from "@kiwicom/orbit-components/lib/Text"

type Props = {|
  // won't pass
  type: string
|}

const WrappedText = ({ children, type }) => 
  <Text type={type}>{children}</Text>

export default WrappedText

```

This change would allow our consumers to easily import and use them in their abstraction:
```js
import type { Type } from "@kiwicom/orbit-components/lib/Text"
import Text from "@kiwicom/orbit-components/lib/Text"

type Props = {|
   type: Type
|}

const WrappedText = ({ children, type }) => 
  <Text type={type}>{children}</Text>

export default WrappedText
```

As starting candidates for this are these components and their enums/unions:
- Text: Weight and Type
- Illustration: Name
- Alert: Type
- Popover: AlignsCore (used for preferredAlign)
- Badge: Type
- TextLink: Type

This list would a good start and we can iterate later.

As this will become the official API of `@kiwicom/orbit-components` we have to document them. Possibly, we can just add note to the components markdown files, something like this:
```markdown
// rest of the markdown content
### Types
You can import these types from type definitions of this component.
import type { Type } from "@kiwicom/orbit-components/lib/Text" // Flow
import { Type } from "@kiwicom/orbit-components/lib/Text" // TS
```

**Comment by aalises** [comment]
@vepor any idea why are we putting 

```js
src/Illustration/index.js.flow
src/Illustration/index.d.ts
```

into `.gitignore`?

**Comment by vepor** [comment]
It's being autogenerated, because of e.g. `type Name`, so we don't have to maintain it in multiple files, when we need to add some new Illustration.

**Comment by vepor** [comment]
You can alter the `FLOW_TEMPLATE.flow` if you want to make some changes to the generated file. You can generate it then with `build` script.
