### ISSUE TITLE
Remove all sizes from AlertButton besides small

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit#2307]
We currently offer a possibility to have different sizes on `AlertButton` component, but from design perspective only `small` is feasible. Therefore we can do a breaking change and delete `normal` and `large` size from this component and make `small` as the default and only one.

**Comment by MuhammadTanveer94** [comment]
Hi i would like to do this @vepor ?

**Comment by vepor** [comment]
Hi @MuhammadTanveer94 👋 , feel free to do it! 🙂

**Comment by vepor** [comment]
Hello @MuhammadTanveer94 , any update here? 🙂 If you won't have time to create PR for this issue, please let me know. 🙏

**Comment by ggolubic** [comment]
Hey, I can take it if @MuhammadTanveer94 won't have time :)

**Comment by MuhammadTanveer94** [comment]
Sure you can and sorry from my side i am too buzy and don't have time to do this

Sent from Yahoo Mail on Android 
 
  On Wed, Oct 21, 2020 at 8:43 PM, Gabrijel Golubić<notifications@github.com> wrote:   


Hey, I can take it if @MuhammadTanveer94 won't have time :)
