### ISSUE TITLE
Fix padding on InputField suffix

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit#2308]
As seen at [orbit.kiwi](https://orbit.kiwi/components/inputfield/#suffixes), text suffixes for InputFields don't have the proper right padding and overlap the edge of the field.

**Comment by simonhoyos** [comment]
@vepor I can help with this one

**Comment by vepor** [comment]
Hey @simonhoyos 👋 , feel free to do so! We will be more than glad to have it done 🙂

**Comment by simonhoyos** [comment]
Hi @vepor, 

Here are my findings so far about this issue:

1. When checking this component in storybook it is working correctly. The reason for this is that the padding is being set within the suffix prop

```javascript
<InputField
  label={label}
  value={value}
  placeholder={placeholder}
  suffix={<div style={{ paddingRight: "12px" }}>{suffix}</div>}
  onChange={action("change")}
/>
```

2. Adding the following lines to the `Suffix` component fixes the problem, but it changes the behavior of the `ButtonLink suffix`:

```diff
+ padding: ${getPadding()};
+ padding-left: 0;
```

**Current ButtonLink state:**
![image](https://user-images.githubusercontent.com/23706543/95514310-55cf1d00-0981-11eb-823f-0bf734284cc2.png)

**After proposed changes:**
![image](https://user-images.githubusercontent.com/23706543/95514365-6b444700-0981-11eb-97fe-8d3dbb1e0184.png)

As you can see the right spacing is bigger after changes.

Some alternatives include:
1. Adding to the documentation that padding should be added to the suffix.
2. Adding a prop flag that adds/removes padding.

Let me know what you think.

**Comment by vepor** [comment]
Thanks a lot @simonhoyos! 🙂 

I don't think that we want to implement a change for the ButtonLink. Therefore could you please a PR that will fix mentioned example, that is currently wrong? 🙏 It should be [this file](https://github.com/kiwicom/orbit/blob/master/packages/orbit-components/src/InputField/__examples__/SUFFIX.js).

**Comment by simonhoyos** [comment]
> Thanks a lot @simonhoyos! 🙂
> 
> I don't think that we want to implement a change for the ButtonLink. Therefore could you please a PR that will fix mentioned example, that is currently wrong? 🙏 It should be [this file](https://github.com/kiwicom/orbit/blob/master/packages/orbit-components/src/InputField/__examples__/SUFFIX.js).

Great! I'll start working on that ASAP

**Comment by CollierCZ** [comment]
@vepor, you think it's the correct behavior to force people to add custom styling for any use of suffix? It seems to me that a much more sustainable solution would be adjusting the [styling that is a part of InputField](https://github.com/kiwicom/orbit/blob/master/packages/orbit-components/src/InputField/index.js#L184). It could include different styling for different suffixes, but asking people to input custom styling seems not very user-friendly.

**Comment by vepor** [comment]
Sadly, it's the official way how to do it for a long period of time.

I'm afraid that we can't simply put a condition to the `Suffix` component as it could lead to more problems than fixes. And in the end, it would a breaking change for a lot of implementation. Because external contributors can't simply validate if the fix works properly I would like to do it in a separate ticket, our of the scope of this issue.
