### ISSUE TITLE
Refactor Modal component to use only React hooks

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit#2309]
`Modal` component is one of the last that uses React Class component.
This complicates other improvements we want to make to the Modal component, as general API refactor, animations etc. and therefore the best would be to refactor it to use only the React hooks.

**Comment by zurda** [comment]
Hi @vepor , I'd like to help out with this if it's up for grabs?

**Comment by MuhammadTanveer94** [comment]
Hi I would like to do this @vepor ?

**Comment by vepor** [comment]
Hello @zurda, it's up for grabs, definitely! 🙂 We will be more than happy to have it done by you 🙂

**Comment by vepor** [comment]
Hello @zurda, any update here? 🙂 If you won't have time to create PR for this issue, please let me know. 🙏

**Comment by zurda** [comment]
Hi @vepor, apologies for the delay. 
This is mostly done but I wanted to take a look at a few more life cycle methods refactoring before submitting. 
I'll be sure to submit the pr this weekend if that's OK

**Comment by vepor** [comment]
No problem at all @zurda, just wanted to know the status 🙂

**Comment by zurda** [comment]
Hi @vepor , thanks for the reminder and unfortunately I haven't managed to get this to a PR state and I've released it so I'm not blocking the issue for others

**Comment by vepor** [comment]
Thanks @zurda anyway! Looking forward to maybe different contributions you might make 🙂
