### ISSUE TITLE
Add react-axe as plugin to Storybook

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit#2318]
Because of a11y reasons, it would be great to add `react-axe` as accessibility checker for both the production and development build.

**Comment by sanskar-p** [comment]
Hi @vepor, I'd like to try my hands at this issue. I'm planning on referring to [this](https://web.dev/accessibility-auditing-react/) link. What do you think?

**Comment by vepor** [comment]
Hey @sanskar-p 👋 

We are already using `eslint-plugin-jsx-a11y` for the `@kiwicom/orbit-components`, but feel free to get your hands on `react-axe` and integrate it with `storybook`! 🙂

**Comment by sanskar-p** [comment]
@vepor, can you give me some advice on how to do that?

**Comment by vepor** [comment]
What we want to do here is to add the `react-axe` to be loaded with the storybook.
This can be easily implemented into `[preview.js](https://github.com/kiwicom/orbit/blob/master/packages/orbit-components/.storybook/preview.js)` file.

It can be implemented as [a addon](https://github.com/storybookjs/storybook/tree/master/addons/a11y#getting-started) or just used with [normal import](https://github.com/dequelabs/react-axe#initialize-the-module).

Let me know @sanskar-p if will do this, otherwise somebody else or our core team can handle it.

**Comment by sanskar-p** [comment]
@vepor, will it work to just insert this codeblock into `preview.js`?
```
var React = require('react');
var ReactDOM = require('react-dom');

if (process.env.NODE_ENV !== 'production') {
  var axe = require('react-axe');
  axe(React, ReactDOM, 1000);
}
```
Found it [here](https://github.com/dequelabs/react-axe#initialize-the-module)

**Comment by vepor** [comment]
Yes, it should @sanskar-p 🙂 

Also it seems that `react-axe` is deprecated, so it would be better to use `@axe-core/react` instead, so we will get updates in the future.

**Comment by aalises** [comment]
@sanskar-p also, you can use `ES6` syntax, e.g.

```js
import { addDecorator, addParameters } from "@storybook/react";
import * as React from "react";
import * as ReactDOM from "react-dom";

import "loki/configure-react";
import orbitTheme from "./orbitTheme";
import orbitDecorator from "./orbitDecorator";

if (process.env.NODE_ENV !== "production") {
  import("@axe-core/react").then(axe => axe(React, ReactDOM, 1000));
}
```

**Comment by mainframev** [comment]
Also check this [addon-a11y](https://www.npmjs.com/package/@storybook/addon-a11y). It has `axe` under the hood

**Comment by tbergq** [comment]
> Also check this [addon-a11y](https://www.npmjs.com/package/@storybook/addon-a11y). It has `axe` under the hood

This is probably the best choice 🙂 It seems to be better adapted for storybook.
