### ISSUE TITLE
Enforce with ESLint that all types should be read-only and exact

### ISSUE THREAD

**Issue by silvenon** [kiwicom/orbit#2327]
Our convention for Flow and TypeScript is to write exact and read-only types, but nothing is enforcing this, so we definitely forgot to do this in some places. This can be solved with ESLint (TypeScript is already exact, so there we just need read-only).

**Comment by aalises** [comment]
I can take this: `typescript-eslint` has the `prefer-readonly-parameter-types` rule. (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-readonly-parameter-types.md), and for `private` members. (https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-readonly.md) 

I don't know if that's what we are exactly looking for though...

**Comment by silvenon** [comment]
Thanks! For TypeScript we only need `readonly`, and would you be willing to enforce Flow as well via [`require-exact-type`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-exact-type) and [`require-readonly-react-props`](https://github.com/gajus/eslint-plugin-flowtype#require-readonly-react-props)? It appears that the Flow plugin only supports enforcing readonly for React props (and for arrays, but no need to bother with that for now).
