### ISSUE TITLE
Prohibit usage of global React Flow types (e.g. React$Node)

### ISSUE THREAD

**Issue by silvenon** [kiwicom/orbit#2345]
Global React Flow types are never mentioned in the Flow documentation, which strongly suggests that they don't like people using them. Also, using them in Orbit apparently caused some problems for others, so we should definitely stop using them and prohibit their usage via ESLint. However, I'm not aware of any ESLint rule that can do this, maybe there is one, I haven't thoroughly checked, but in case there isn't it should this is a great opportunity to learn how to build one because as far as complexity goes, this should be one of the simpler ones. ESLint has great documentation for [working with rules](https://eslint.org/docs/developer-guide/working-with-rules) and [testing them](https://eslint.org/docs/developer-guide/unit-tests), and [AST explorer](https://astexplorer.net/) is your friend here.

**Comment by sampi** [comment]
I'll take this real quick ;)
