### ISSUE TITLE
Remove code blocks from visual regression testing

### ISSUE THREAD

**Issue by silvenon** [kiwicom/orbit#2346]
We're using [Loki](https://www.npmjs.com/package/loki) for visual regression testing. Currently our screenshots include code blocks, which is a bit problematic because it increases the number of false positives. When we change the code a bit but the output of the component hasn't changed, that's still being treated as a visual regression, which slows down publishing a new release. It would be great if we can somehow remove code blocks while performing visual regression testing.

**Comment by sampi** [comment]
I'll take a look
