### ISSUE TITLE
New accordion Component docs

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit#2359]
Hello, 
im happy to see more components added , i was reading the docs about accordion component and just found a tiny error in the docs.
the prop expanded of type bool with default property of 0
i think it's better to have false instead ,
thank You

**Comment by vepor** [comment]
Could you prepare fixing pull request for that @kouloughli-hemza, please? 🙏

**Comment by kouloughli-hemza** [comment]
> Could you prepare fixing pull request for that @kouloughli-hemza, please?

#2362
