### ISSUE TITLE
Avoid unnecessary version bumps of @kiwicom/babel-plugin-orbit-components

### ISSUE THREAD

**Issue by silvenon** [kiwicom/orbit#2368]
`@kiwicom/babel-plugin-orbit-components` always gets a version bump because it has `@kiwicom/orbit-components` in `devDependencies`. It will probably be enough to remove it, otherwise we should consider removing all `devDependencies` from both packages.

Success can be checked by running `yarn release`, then seeing whether the version is unjustifiably bumped.

lerna/lerna#1737

**Comment by sampi** [comment]
I'll take a look, if it can be done quickly
