### ISSUE TITLE
Add offset property to Popover

### ISSUE THREAD

**Issue by vepor** [kiwicom/orbit#2378]
Currently, the Popover is rendered exactly on the bottom position of parent component – that triggers the render of it.

Because of design purposes, the best would be to add property that would allow developers to easily tweak the exact position, probably in pixels.

The usage would look like this:
```
const offset = { left: 2, top: 2 }

<Popover content={content} offset={offset}>
  <Button />
</Popover>
````

It need to be tested properly with usage of `preferredAlign` and `preferredPosition`.

**Comment by mainframev** [comment]
> hey @vepor , "It need to be tested properly with usage of preferredAlign and preferredPosition. " will you please describe how to do it?

👋🏻  

hi :)

preferredAlign and preferredPosition props are no more existing in Popover. They were replaced by placement property in #3046. Now our Popover uses Popper. And you can read about offset and placement in their documentation
