### ISSUE TITLE
Feature request: allow fixed ModalHeader

### ISSUE THREAD

**Issue by skmohammadi** [kiwicom/orbit#2632]
It seems `fixedFooter` property cause `ModalFooter` to be fixed but, in mobile `ModalHeader` do not get fixed position.

## Expected Behavior

`ModalHeader` be fixed in mobile when scrolling down.

## Current Behavior

only `ModalFooter` has fixed position on scrolling.

## Context (Environment)

I am using React 17 with NextJS.

**Comment by CollierCZ** [comment]
Could you describe your use case a little more? Modal footers are generally where actions are held, so it makes sense to keep them fixed and accessible. What is in the header that you would like to keep fixed?

**Comment by skmohammadi** [comment]
Hi. It seems the problem is solved. thanks
