### ISSUE TITLE
Datepicker and pricing/departure table

### ISSUE THREAD

**Issue by mapsgeek** [kiwicom/orbit#2780]
**Is your feature request related to a problem? Please describe.**

Having a datepicker is crucial for any travelling/booking app, do you have any plans for adding that?
also the component pricing table is quite deceiving to me, that's because i expected to find
the pricing table from kiwi.com results page but instead i find the docs showing a generic 3 column layout to show product plans, this component really looks and functions so good and would be very nice to have.

**Describe the solution you'd like**
Providing a road trip for any components that would be added in the future so people can decide if they can actually
depend on the design system and its UI components or whether if they will need 3rd party ones.

**Describe alternatives you've considered**
I'm considering using Airbnb datepicker and design my own departure/prices table, which wouldn't be ideal because i think it defeats the purpose of using a unified design system

**Additional context**
Thank you

**Comment by CollierCZ** [comment]
Hi. We have a public roadmap of what we're planning on working on: https://orbit.kiwi/roadmap/. I'd say that at this time, a date picker and the price table aren't in the near-term plans. We're currently developing components for itineraries. The PricingTable component that we currently have will likely be deprecated.
