### ISSUE TITLE
textlink onClick when stopPropagation call two time

### ISSUE THREAD

**Issue by straxico** [kiwicom/orbit#2853]
textlink onClick when stopPropagation enable call two time

need use else

```
  const onClickHandler = ev => {
    if (stopPropagation) {
      ev.stopPropagation();
      if (onClick) onClick(ev);
    }
    if (onClick) onClick(ev);
  };
```
https://github.com/kiwicom/orbit/blob/7b1152bb9372d9ab2824000c59e9181ce9a9f65d/packages/orbit-components/src/TextLink/index.js#L124

**Comment by vepor** [comment]
You're right @straxico, thanks for the bug report! 🙂 

Let me prepare a quick fix for this 💪
