### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by pierceglennie** [kiwicom/orbit#2858]
**Is your feature request related to a problem? Please describe.**
Using Orbit is stopping us from upgrading to React 17 (using npm 7) since it has a peer dependency on React ^16.14.0

**Describe the solution you'd like**
Update peer dependency to allow React 17. React 17 has minimal breaking changes so my guess is that this would not require big changes.

**Comment by mainframev** [comment]
hi @pierceglennie 

We glad that you use orbit. My apologies for the delayed response, we had other prios. We will update it most likely next week :)

**Comment by pierceglennie** [comment]
Thanks, it's been really helpful so far – saves us reinventing the wheel. In case you're interested we're using it at www.ember.to (electric bus service). And thanks for the update on React 17 support

**Comment by silvenon** [comment]
React 17 update has been merged, it will be available in the next release. 😃

**Comment by pierceglennie** [comment]
Nice one, thanks
