### ISSUE TITLE
Add option to navigation bar to not hide on scroll

### ISSUE THREAD

**Issue by mapsgeek** [kiwicom/orbit#2906]
**Is your feature request related to a problem? Please describe.**
I'm trying to not hide the Navbar on scroll but i'm not sure if this can be achieved with the `onHide` prop

**Describe the solution you'd like**
pass a prop `scrollHide={true/false}` and this would control the option to make it hide or not"
or provide an example on how to do that using the current props.

**Comment by mainframev** [comment]
Hi, I will add a new prop `hideOnScroll` which you will have to set explicitly to `false`. ;)

**Comment by mainframev** [comment]
solved in #3282
