### ISSUE TITLE
docs: some Figma iframes require logging in

### ISSUE THREAD

**Issue by CollierCZ** [kiwicom/orbit#3075]
The idea to have text separate from Figma images seems like potentially a nice one, but the iframe for the [badge content structure](https://beta.orbit.kiwi/components/information/badge/#content-structure) requires me to be logged in to view.

**Comment by silvenon** [comment]
> The idea to have text separate from Figma images seems like potentially a nice one

What are you referring to here exactly? This part?

> 1. Icon (Supports the label)
> 2. Label (Works best when short)

**Comment by williamkolmacka** [comment]
@CollierCZ we will probably export only images from the Figma instead of Figma frames here, as there is a problem with showing the content on 100% of its real size + as you mentioned, it's a bit difficult to have these files publicly accessible. Thanks for the feedback 👍

**Comment by CollierCZ** [comment]
@silvenon 

> What are you referring to here exactly? This part?

Yes, that part. I don't know what it actually looks like, because I'm not in Figma, but I assume it's something like in [Carbon](https://www.carbondesignsystem.com/components/accordion/usage/#anatomy).

@williamkolmacka, sounds good 👍

**Comment by ross-weir** [comment]
This looks like it might be a problem again, there's a number of these in the docs for me currently:

<img width="903" alt="orbit-figma-login" src="https://user-images.githubusercontent.com/29697678/143670619-f67403f0-31ec-4301-a9e5-b36cd822849c.PNG">

Logging in doesn't allow me to view so they might be private ones

**Comment by silvenon** [comment]
@ross-weir thanks for reporting, we'll discuss what we can do.

**Comment by silvenon** [comment]
We fixed it by making the Figma file public 🚀 Let us know if you find more closed ones.

**Comment by CollierCZ** [comment]
@silvenon , there are three on the Button page alone (was just looking at it): https://orbit.kiwi/components/action/button/

**Comment by silvenon** [comment]
Fixed!
