### ISSUE TITLE
Possibility to set timeline direction

### ISSUE THREAD

**Issue by kouloughli-hemza** [kiwicom/orbit#3308]
**Is your feature request related to a problem? Please describe.**
Currently, the timeline in Desktop view is in rows, and when we have a lot of TimelineStep it gets messy .

**Describe the solution you'd like**
 I would like to show the mobile style of timeline on desktop view.

**Comment by mainframev** [comment]
Hi @kouloughli-hemza 
Yep, we will adjust the behavior for desktop 👍🏻

**Comment by mainframev** [comment]
solved in #3382
