### ISSUE TITLE
Search shortcut (⌘ + K) doesn't work properly on FF

### ISSUE THREAD

**Issue by mvidalgarcia** [kiwicom/orbit#3542]
From Firefox browser, the search shortcut (⌘ + K) on orbit.kiwi [opens the browser address bar with the Default search engine](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly).

## Expected Behavior

It should ignore the Firefox shortcut and just use the Orbit one. Other websites such as https://tailwindcss.com/ manage it properly, so it should be feasible.

## Current Behavior

Opens up the browser address bar and sets focus on it.

## Possible Solution

There should be a way to disable certain browser shortcuts. Some input: https://stackoverflow.com/questions/24764626/any-way-to-prevent-disable-ctrl-key-shortcuts-in-the-browser

## Steps to Reproduce

1. Open FF browser
2. Go to orbit.kiwi
3. Enter ⌘ + K

**Comment by mainframev** [comment]
@mvidalgarcia  👋🏻  thanks, we are already aware of it, just did not have time to fix that. There are other options, like on the screenshot below
![Screenshot 2022-07-27 at 13 59 20](https://user-images.githubusercontent.com/14054752/181241549-d1a496a0-4008-40ad-a193-4c5455d0e5d5.png)

**Comment by mainframev** [comment]
@mvidalgarcia oh, sorry, I meant options to add, currently cmd + shift is not added. This screenshot is from GitHub because they have a similar issue with FF. So I will add cmd + shift + k. and maybe some fallback for Edge 🤔

**Comment by mvidalgarcia** [comment]
I see this is implemented, thanks!
Closing it...
