### ISSUE TITLE
Unable to remove white background on corners of Select component

### ISSUE THREAD

**Issue by statsgod** [kiwicom/orbit#3695]
## Expected Behavior

Because Select components have a round border, the background of its corners should be transparent/show the color of the parent component

https://orbit.kiwi/components/input/select/

## Current Behavior

Select components have the default background color in their colors, which clashes next to other custom colors:
<img width="414" alt="image" src="https://user-images.githubusercontent.com/66491090/208276196-04ec34b1-6c70-4864-b612-7f52a92016e2.png">

## Possible Solution

Seems like it will require fix within orbit as I don't they can be overridden w/ simple css due to: https://orbit.kiwi/development/guides/no-exporting-components/

## Steps to Reproduce

See Select component within a div with a black background here:
https://codesandbox.io/s/interesting-mclean-qyo87j?file=/src/index.js

## Context (Environment)

Problem I'm facing is having to worry about matching all of the Orbit default colors next to each of my custom components. In many cases, the colors will just match but would rather not have to do that explicitly vs being able to rely on transparency.

**Comment by DSil** [comment]
Hi

This is a visual bug. Will be fixed on the next release.
