### ISSUE TITLE
DatePicker Component

### ISSUE THREAD

**Issue by Ahmedbennaji** [kiwicom/orbit#4331]
**Is your feature request related to a problem? Please describe.**

Currently, we don't have a datepicker component in our application, and users are requesting a way to easily select dates for various tasks and activities. This makes it challenging for users to input dates accurately and efficiently, leading to potential errors and frustration.

**Describe the solution you'd like**
I would like to implement a datepicker component that allows users to easily select dates from a calendar interface. The datepicker should be intuitive to use, visually appealing, and customizable to fit our application's design and functionality requirements. It should support selecting single dates, date ranges, and disabling certain dates based on predefined criteria. Additionally, it should provide options for localization, accessibility, and keyboard navigation to ensure a seamless user experience across different devices and platforms.

**Describe alternatives you've considered**
One alternative solution is to rely on input fields for date entry, but this approach can be cumbersome and error-prone, especially for users who are not familiar with date formats or have difficulty typing accurately. Another option is to use third-party datepicker libraries, but these may not fully meet our application's requirements or may introduce dependencies and integration challenges.

**Additional context**
Our application frequently requires users to input dates for scheduling appointments, booking reservations, setting deadlines, and other tasks. A datepicker component would greatly improve the user experience and streamline these processes, leading to increased user satisfaction and productivity.

**Comment by mvidalgarcia** [comment]
Hi @Ahmedbennaji, thanks so much for your detailed proposal.

While having a datepicker in Orbit would make sense, unfortunately we don't have the capacity to deal with this request at the moment. Our product has already datepickers implemented internally so this is not critical for us right now.

Said that, if we had to implement our datepicker at this moment, we would probably rely on something like https://ui.shadcn.com/docs/components/date-picker, as you can _download_ the implementation (no third-part libraries) and customize it to your taste.
