### ISSUE TITLE
[Popover]: "Invalid DOM property `popovertarget`. Did you mean `popoverTarget`" get warning in Next.js 15/React 19

### ISSUE THREAD

**Issue by soulasid** [kiwicom/orbit#4564]
I am using the Popover component from @kiwicom/orbit-components in a Next.js 15 project. Upon rendering the Popover with the popoverTarget prop, React throws the following warning:
`Warning: Invalid DOM property `popovertarget`. Did you mean `popoverTarget`?`
### Environment Details
1. Browser: Chrome 117.0.0 
2. Next.js version: 15.1.3
3. React version: 19.0.0
4. @kiwicom/orbit-components version: 18.2.0

**Comment by DSil** [comment]
Hi @soulasid 

`popovertarget` **is** a valid DOM property ([source](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API/Using)).

I can't get the same warning as you, but I do get another warning, regarding the `popover` property. We will revisit these properties soon, with low priority, as the warning are in dev mode only and are not having any effect in production.
