### ISSUE TITLE
Fix flow types for styled components

### ISSUE THREAD

**Issue by VaclavSir** [kiwicom/orbit#856]
There are two definitions of `styled-components` installed:

- [styled-components_v3.x.x.js](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/styled-components_v3.x.x/flow_v0.75.x-/styled-components_v3.x.x.js) - definition for an older version (Orbit already uses 4.x.x)
- [styled-components_vx.x.x.js](https://github.com/kiwicom/orbit-components/blob/master/flow-typed/npm/styled-components_vx.x.x.js) - stub that declares all modules as `any`

It looks like the `vx.x.x` stub is used and the `v3.x.x` is ignored. Because when I delete the stub, I get 80 flow errors.

When I delete both definitions and install `v4.x.x` (`flow-typed install styled-components@4`), I get 268 flow errors (restart of the Flow server was needed for this - `yarn flow stop && yarn flow`).

## Expected Behavior

Components are typed properly.

## Current Behavior

Some components look like properly typed (eg. when they use the type `ReactComponentStyled`), but are in fact typed as `any` (because `styled-components` is `any`, therefore `ReactComponentStyled` is also `any`).

## Possible Solution

1) Delete the confusing unused definition for 3.x.x version, keep the stub
2) Remove all `import type ... from "styled-components";`
3) Use React types instead (eg. `React.ComponentType` instead of `ReactComponentStyled`)

**Comment by jaroslav-kubicek** [comment]
hej! 👋 

I got into trouble with this today with flowconfig as below and `flow-typed install styled-components@4`

```
[ignore]
<PROJECT_ROOT>/node_modules/mapbox-gl/*
<PROJECT_ROOT>/node_modules/@mapbox

[include]

[libs]
<PROJECT_ROOT>/flow-typed

[lints]
; make sure to turn on at least "untyped-type-import"
all=error
implicit-inexact-object=off
dynamic-export=off
non-array-spread=off
sketchy-null-bool=off
unclear-type=off
untyped-import=warn

[strict]
implicit-inexact-object
sketchy-null-bool
unclear-type
untyped-import

[options]
emoji=true
include_warnings=true
module.ignore_non_literal_requires=true
esproposal.optional_chaining=enable
esproposal.nullish_coalescing=enable

suppress_comment=\\(.\\|\n\\)*\\$FlowExpectedError: .+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe: .+
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue: https://github.com/facebook/flow/issues/[0-9]+
```
